import type { Product } from "./types.js";

export const DEMO_PRODUCTS: Product[] = [
  // ─── DRINKS ──────────────────────────────────────────────────────────────
  {
    id: "drink-001",
    name: "Suntory BOSS Rainbow Mountain Blend",
    nameJa: "サントリーBOSS レインボーマウンテンブレンド",
    brand: "Suntory",
    category: "drinks",
    store: "7-Eleven",
    priceJpy: 148,
    volumeMl: 185,
    weightG: null,
    servings: 1,
    nutrition: {
      calories: 61,
      protein: null,
      fat: null,
      carbs: null,
      sugar: null,
      sodium: null,
      caffeine: 65,
      fiber: null,
    },
    skincare: null,
    allergens: [],
    additives: ["caramel color", "emulsifier"],
    tags: ["coffee", "canned", "convenience", "classic"],
  },
  {
    id: "drink-002",
    name: "Ito En Oi Ocha Green Tea",
    nameJa: "伊藤園 お～いお茶 緑茶",
    brand: "Ito En",
    category: "drinks",
    store: "FamilyMart",
    priceJpy: 130,
    volumeMl: 500,
    weightG: null,
    servings: 1,
    nutrition: {
      calories: 0,
      protein: 0,
      fat: 0,
      carbs: 0,
      sugar: 0,
      sodium: 0,
      caffeine: 35,
      fiber: null,
    },
    skincare: null,
    allergens: [],
    additives: [],
    tags: ["green tea", "zero calorie", "no sugar", "natural"],
  },
  {
    id: "drink-003",
    name: "Pocari Sweat Ion Supply Drink",
    nameJa: "ポカリスエット イオンサプライ",
    brand: "Otsuka",
    category: "drinks",
    store: "Lawson",
    priceJpy: 138,
    volumeMl: 500,
    weightG: null,
    servings: 1,
    nutrition: {
      calories: 125,
      protein: null,
      fat: null,
      carbs: 31.5,
      sugar: 31,
      sodium: 250,
      caffeine: 0,
      fiber: null,
    },
    skincare: null,
    allergens: [],
    additives: ["citric acid", "potassium chloride"],
    tags: ["sports", "isotonic", "electrolytes", "no caffeine"],
  },
  {
    id: "drink-004",
    name: "Monster Energy Ultra Zero",
    nameJa: "モンスターエナジー ウルトラゼロ",
    brand: "Monster Beverage",
    category: "drinks",
    store: "7-Eleven",
    priceJpy: 230,
    volumeMl: 355,
    weightG: null,
    servings: 1,
    nutrition: {
      calories: 10,
      protein: null,
      fat: null,
      carbs: null,
      sugar: 0,
      sodium: null,
      caffeine: 142,
      fiber: null,
    },
    skincare: null,
    allergens: [],
    additives: [
      "niacinamide",
      "pantothenic acid",
      "sucralose",
      "acesulfame K",
      "taurine",
      "ginseng extract",
    ],
    tags: ["energy", "zero sugar", "high caffeine", "vitamin"],
  },
  {
    id: "drink-005",
    name: "Kirin Gogo-no-Kocha Straight Tea",
    nameJa: "キリン 午後の紅茶 ストレートティー",
    brand: "Kirin",
    category: "drinks",
    store: "Supermarket",
    priceJpy: 140,
    volumeMl: 500,
    weightG: null,
    servings: 1,
    nutrition: {
      calories: 55,
      protein: null,
      fat: null,
      carbs: 14,
      sugar: 13.5,
      sodium: null,
      caffeine: 30,
      fiber: null,
    },
    skincare: null,
    allergens: [],
    additives: ["vitamin C"],
    tags: ["black tea", "mild caffeine", "light sweet"],
  },
  {
    id: "drink-006",
    name: "Dydo Blend Black Coffee",
    nameJa: "DyDo ブレンドブラック",
    brand: "Dydo",
    category: "drinks",
    store: "Vending Machine",
    priceJpy: 120,
    volumeMl: 185,
    weightG: null,
    servings: 1,
    nutrition: {
      calories: 5,
      protein: null,
      fat: null,
      carbs: null,
      sugar: 0,
      sodium: null,
      caffeine: 75,
      fiber: null,
    },
    skincare: null,
    allergens: [],
    additives: [],
    tags: ["coffee", "black", "no sugar", "canned"],
  },
  {
    id: "drink-007",
    name: "Aquarius Zero Sports Drink",
    nameJa: "アクエリアス ゼロ",
    brand: "Coca-Cola Japan",
    category: "drinks",
    store: "FamilyMart",
    priceJpy: 140,
    volumeMl: 500,
    weightG: null,
    servings: 1,
    nutrition: {
      calories: 0,
      protein: null,
      fat: null,
      carbs: 0,
      sugar: 0,
      sodium: 120,
      caffeine: 0,
      fiber: null,
    },
    skincare: null,
    allergens: [],
    additives: ["citric acid", "sucralose", "acesulfame K"],
    tags: ["sports", "zero calorie", "no caffeine", "electrolytes"],
  },

  // ─── SNACKS ──────────────────────────────────────────────────────────────
  {
    id: "snack-001",
    name: "Calbee Jagarico Salted Butter",
    nameJa: "カルビー じゃがりこ バター塩味",
    brand: "Calbee",
    category: "snacks",
    store: "7-Eleven",
    priceJpy: 148,
    volumeMl: null,
    weightG: 58,
    servings: 1,
    nutrition: {
      calories: 310,
      protein: 2.9,
      fat: 17.4,
      carbs: 36.5,
      sugar: 1.8,
      sodium: 370,
      caffeine: null,
      fiber: 1.5,
    },
    skincare: null,
    allergens: ["milk", "wheat"],
    additives: ["seasoning (amino acids)", "flavor"],
    tags: ["potato", "salty", "crispy", "popular"],
  },
  {
    id: "snack-002",
    name: "FamilyMart Original Onigiri Tuna Mayo",
    nameJa: "ファミマ ツナマヨおにぎり",
    brand: "FamilyMart",
    category: "snacks",
    store: "FamilyMart",
    priceJpy: 150,
    volumeMl: null,
    weightG: 110,
    servings: 1,
    nutrition: {
      calories: 200,
      protein: 5.5,
      fat: 4.7,
      carbs: 34.8,
      sugar: null,
      sodium: 510,
      caffeine: null,
      fiber: null,
    },
    skincare: null,
    allergens: ["wheat", "egg", "fish"],
    additives: ["amino acids"],
    tags: ["onigiri", "rice ball", "meal", "convenient"],
  },
  {
    id: "snack-003",
    name: "Meiji Chocolate Bar Milk",
    nameJa: "明治 ミルクチョコレート",
    brand: "Meiji",
    category: "snacks",
    store: "Lawson",
    priceJpy: 148,
    volumeMl: null,
    weightG: 50,
    servings: 1,
    nutrition: {
      calories: 265,
      protein: 4,
      fat: 16.2,
      carbs: 28,
      sugar: 26.8,
      sodium: 55,
      caffeine: 15,
      fiber: null,
    },
    skincare: null,
    allergens: ["milk", "soy"],
    additives: ["lecithin", "vanilla flavor"],
    tags: ["chocolate", "sweet", "snack", "dessert"],
  },
  {
    id: "snack-004",
    name: "Lawson Chicken Lattice (Kara-age-kun)",
    nameJa: "ローソン からあげクン レギュラー",
    brand: "Lawson",
    category: "snacks",
    store: "Lawson",
    priceJpy: 230,
    volumeMl: null,
    weightG: 100,
    servings: 1,
    nutrition: {
      calories: 248,
      protein: 15.3,
      fat: 14.3,
      carbs: 14.5,
      sugar: null,
      sodium: 550,
      caffeine: null,
      fiber: null,
    },
    skincare: null,
    allergens: ["wheat", "soy", "chicken"],
    additives: ["amino acids", "sodium phosphate"],
    tags: ["hot food", "protein", "savory", "fried"],
  },
  {
    id: "snack-005",
    name: "Tohato Caramel Corn",
    nameJa: "東ハト キャラメルコーン",
    brand: "Tohato",
    category: "snacks",
    store: "Supermarket",
    priceJpy: 120,
    volumeMl: null,
    weightG: 77,
    servings: null,
    nutrition: {
      calories: 400,
      protein: 3.7,
      fat: 17.1,
      carbs: 59,
      sugar: 27,
      sodium: 195,
      caffeine: null,
      fiber: null,
    },
    skincare: null,
    allergens: ["milk", "wheat", "peanuts"],
    additives: ["caramel color", "flavor"],
    tags: ["sweet", "crunchy", "snack", "popular"],
  },
  {
    id: "snack-006",
    name: "7-Eleven Salad Chicken Plain",
    nameJa: "7プレミアム サラダチキン プレーン",
    brand: "7-Eleven",
    category: "snacks",
    store: "7-Eleven",
    priceJpy: 248,
    volumeMl: null,
    weightG: 115,
    servings: 1,
    nutrition: {
      calories: 121,
      protein: 25.4,
      fat: 1.9,
      carbs: 0.8,
      sugar: null,
      sodium: 505,
      caffeine: null,
      fiber: null,
    },
    skincare: null,
    allergens: ["chicken"],
    additives: ["sodium phosphate"],
    tags: ["high protein", "low calorie", "diet", "chicken"],
  },
  {
    id: "snack-007",
    name: "Glico Pretz Salted",
    nameJa: "グリコ プリッツ 塩",
    brand: "Glico",
    category: "snacks",
    store: "FamilyMart",
    priceJpy: 100,
    volumeMl: null,
    weightG: 50,
    servings: null,
    nutrition: {
      calories: 214,
      protein: 4.3,
      fat: 5.5,
      carbs: 36.6,
      sugar: 1.2,
      sodium: 350,
      caffeine: null,
      fiber: null,
    },
    skincare: null,
    allergens: ["wheat", "milk", "soy"],
    additives: [],
    tags: ["biscuit stick", "salty", "light", "shareable"],
  },

  // ─── SUPPLEMENTS ─────────────────────────────────────────────────────────
  {
    id: "supp-001",
    name: "Fancl Multivitamin 30 Day Pack",
    nameJa: "ファンケル マルチビタミン 30日分",
    brand: "Fancl",
    category: "supplements",
    store: "Drugstore",
    priceJpy: 980,
    volumeMl: null,
    weightG: null,
    servings: 30,
    nutrition: {
      calories: null,
      protein: null,
      fat: null,
      carbs: null,
      sugar: null,
      sodium: null,
      caffeine: null,
      fiber: null,
    },
    skincare: null,
    allergens: [],
    additives: ["cellulose", "silicon dioxide"],
    tags: ["vitamin", "daily", "additive-minimal", "quality"],
  },
  {
    id: "supp-002",
    name: "Oronamin C Drink",
    nameJa: "オロナミンC ドリンク",
    brand: "Otsuka",
    category: "supplements",
    store: "7-Eleven",
    priceJpy: 88,
    volumeMl: 120,
    weightG: null,
    servings: 1,
    nutrition: {
      calories: 60,
      protein: null,
      fat: null,
      carbs: null,
      sugar: null,
      sodium: null,
      caffeine: 30,
      fiber: null,
    },
    skincare: null,
    allergens: [],
    additives: ["citric acid", "vitamin B group", "caramel color"],
    tags: ["vitamin C", "energy", "classic", "carbonated"],
  },
  {
    id: "supp-003",
    name: "Meiji Amino Collagen Powder",
    nameJa: "明治 アミノコラーゲン パウダー",
    brand: "Meiji",
    category: "supplements",
    store: "Supermarket",
    priceJpy: 2160,
    volumeMl: null,
    weightG: null,
    servings: 30,
    nutrition: {
      calories: null,
      protein: 5,
      fat: null,
      carbs: null,
      sugar: null,
      sodium: null,
      caffeine: null,
      fiber: null,
    },
    skincare: null,
    allergens: ["fish (collagen source)"],
    additives: ["silicon dioxide"],
    tags: ["collagen", "beauty", "protein", "women"],
  },
  {
    id: "supp-004",
    name: "Chocola BB Plus Vitamin B Complex",
    nameJa: "チョコラBBプラス ビタミンB群",
    brand: "Eisai",
    category: "supplements",
    store: "Drugstore",
    priceJpy: 1280,
    volumeMl: null,
    weightG: null,
    servings: 40,
    nutrition: {
      calories: null,
      protein: null,
      fat: null,
      carbs: null,
      sugar: null,
      sodium: null,
      caffeine: null,
      fiber: null,
    },
    skincare: null,
    allergens: [],
    additives: ["cellulose", "silicon dioxide", "yellow 5"],
    tags: ["vitamin B", "skin health", "fatigue", "popular"],
  },
  {
    id: "supp-005",
    name: "DHC Coenzyme Q10 60 Day Pack",
    nameJa: "DHC コエンザイムQ10 60日分",
    brand: "DHC",
    category: "supplements",
    store: "Drugstore",
    priceJpy: 1482,
    volumeMl: null,
    weightG: null,
    servings: 60,
    nutrition: {
      calories: null,
      protein: null,
      fat: null,
      carbs: null,
      sugar: null,
      sodium: null,
      caffeine: null,
      fiber: null,
    },
    skincare: null,
    allergens: ["soy"],
    additives: ["gelatin", "cellulose", "silicon dioxide"],
    tags: ["antioxidant", "energy metabolism", "heart", "daily"],
  },
  {
    id: "supp-006",
    name: "Amino Vital Gold 3000mg",
    nameJa: "アミノバイタル ゴールド 3000mg",
    brand: "Ajinomoto",
    category: "supplements",
    store: "7-Eleven",
    priceJpy: 298,
    volumeMl: null,
    weightG: null,
    servings: 1,
    nutrition: {
      calories: 10,
      protein: null,
      fat: null,
      carbs: null,
      sugar: null,
      sodium: null,
      caffeine: null,
      fiber: null,
    },
    skincare: null,
    allergens: [],
    additives: ["sweetener (acesulfame K)", "citric acid"],
    tags: ["BCAA", "sports", "recovery", "amino acid"],
  },

  // ─── SKINCARE ────────────────────────────────────────────────────────────
  {
    id: "skin-001",
    name: "Shiseido Senka Perfect Whip Face Wash",
    nameJa: "資生堂 専科 パーフェクトホイップ 洗顔料",
    brand: "Shiseido / Senka",
    category: "skincare",
    store: "Drugstore",
    priceJpy: 748,
    volumeMl: 120,
    weightG: null,
    servings: null,
    nutrition: null,
    skincare: {
      spf: null,
      fragranceFree: false,
      alcoholFree: true,
      irritationRisk: "low",
      keyIngredients: ["silk serum protein", "hyaluronic acid", "squalane"],
    },
    allergens: [],
    additives: [],
    tags: ["face wash", "gentle", "hydrating", "popular"],
  },
  {
    id: "skin-002",
    name: "Biore UV Aqua Rich Watery Essence SPF50+",
    nameJa: "ビオレ UV アクアリッチ ウォータリーエッセンス SPF50+",
    brand: "Biore",
    category: "skincare",
    store: "Supermarket",
    priceJpy: 998,
    volumeMl: 50,
    weightG: null,
    servings: null,
    nutrition: null,
    skincare: {
      spf: 50,
      fragranceFree: false,
      alcoholFree: false,
      irritationRisk: "medium",
      keyIngredients: ["methoxycinnamate", "hyaluronic acid"],
    },
    allergens: [],
    additives: ["alcohol", "fragrance"],
    tags: ["sunscreen", "SPF50+", "lightweight", "bestseller"],
  },
  {
    id: "skin-003",
    name: "Hada Labo Gokujun Hyaluronic Lotion",
    nameJa: "肌ラボ 極潤 ヒアルロン液",
    brand: "Rohto",
    category: "skincare",
    store: "Drugstore",
    priceJpy: 748,
    volumeMl: 170,
    weightG: null,
    servings: null,
    nutrition: null,
    skincare: {
      spf: null,
      fragranceFree: true,
      alcoholFree: true,
      irritationRisk: "low",
      keyIngredients: [
        "hyaluronic acid (4 types)",
        "ceramide",
        "N-acetylglucosamine",
      ],
    },
    allergens: [],
    additives: [],
    tags: ["toner", "hyaluronic acid", "fragrance-free", "sensitive skin"],
  },
  {
    id: "skin-004",
    name: "Curel Moisturizing Face Wash",
    nameJa: "キュレル 潤浸保湿 洗顔料",
    brand: "Kao / Curel",
    category: "skincare",
    store: "Drugstore",
    priceJpy: 1078,
    volumeMl: 150,
    weightG: null,
    servings: null,
    nutrition: null,
    skincare: {
      spf: null,
      fragranceFree: true,
      alcoholFree: true,
      irritationRisk: "low",
      keyIngredients: ["ceramide function ingredient", "dipotassium glycyrrhizate"],
    },
    allergens: [],
    additives: [],
    tags: ["face wash", "sensitive skin", "ceramide", "dermatologist-recommended"],
  },
  {
    id: "skin-005",
    name: "DHC Deep Cleansing Oil",
    nameJa: "DHC 薬用ディープクレンジングオイル",
    brand: "DHC",
    category: "skincare",
    store: "Drugstore",
    priceJpy: 1320,
    volumeMl: 200,
    weightG: null,
    servings: null,
    nutrition: null,
    skincare: {
      spf: null,
      fragranceFree: false,
      alcoholFree: true,
      irritationRisk: "low",
      keyIngredients: ["olive oil", "rosemary extract"],
    },
    allergens: [],
    additives: ["fragrance"],
    tags: ["cleansing oil", "makeup remover", "gentle", "olive oil"],
  },
  {
    id: "skin-006",
    name: "Anessa Perfect UV Sunscreen Skincare Milk SPF50+",
    nameJa: "アネッサ パーフェクトUV スキンケアミルク SPF50+",
    brand: "Shiseido / Anessa",
    category: "skincare",
    store: "Drugstore",
    priceJpy: 2530,
    volumeMl: 60,
    weightG: null,
    servings: null,
    nutrition: null,
    skincare: {
      spf: 50,
      fragranceFree: false,
      alcoholFree: false,
      irritationRisk: "medium",
      keyIngredients: ["titanium dioxide", "zinc oxide", "hyaluronic acid"],
    },
    allergens: [],
    additives: ["alcohol", "fragrance"],
    tags: ["sunscreen", "SPF50+", "water-resistant", "outdoor"],
  },
  {
    id: "skin-007",
    name: "Minon Amino Moist Gentle Wash",
    nameJa: "ミノン アミノモイスト やさしい洗顔料",
    brand: "Daiichi Sankyo",
    category: "skincare",
    store: "Drugstore",
    priceJpy: 1320,
    volumeMl: 150,
    weightG: null,
    servings: null,
    nutrition: null,
    skincare: {
      spf: null,
      fragranceFree: true,
      alcoholFree: true,
      irritationRisk: "low",
      keyIngredients: [
        "11 amino acid moisturizers",
        "glycerin",
        "hyaluronic acid",
      ],
    },
    allergens: [],
    additives: [],
    tags: ["face wash", "amino acid", "fragrance-free", "ultra-sensitive"],
  },

  // ─── HOUSEHOLD ───────────────────────────────────────────────────────────
  {
    id: "house-001",
    name: "Kao Magiclean Toilet Cleaner",
    nameJa: "花王 マジックリン トイレ用洗剤",
    brand: "Kao",
    category: "household",
    store: "Supermarket",
    priceJpy: 248,
    volumeMl: 400,
    weightG: null,
    servings: null,
    nutrition: null,
    skincare: null,
    allergens: [],
    additives: [],
    tags: ["cleaning", "toilet", "effective", "fragrance"],
  },
  {
    id: "house-002",
    name: "Febreze Fabric Deodorant Unscented",
    nameJa: "ファブリーズ 布用 無香料",
    brand: "P&G",
    category: "household",
    store: "7-Eleven",
    priceJpy: 398,
    volumeMl: 370,
    weightG: null,
    servings: null,
    nutrition: null,
    skincare: null,
    allergens: [],
    additives: [],
    tags: ["deodorant", "fabric", "unscented", "odor removal"],
  },
  {
    id: "house-003",
    name: "Scotch Brite Multi-Use Sponge 3 Pack",
    nameJa: "スコッチブライト 多用途スポンジ 3個入り",
    brand: "3M / Scotch Brite",
    category: "household",
    store: "Supermarket",
    priceJpy: 298,
    volumeMl: null,
    weightG: null,
    servings: null,
    nutrition: null,
    skincare: null,
    allergens: [],
    additives: [],
    tags: ["sponge", "kitchen", "value", "durable"],
  },
  {
    id: "house-004",
    name: "Bioré Sarasara UV Body Mist SPF50",
    nameJa: "ビオレ さらさらUV 全身にかけるミスト SPF50",
    brand: "Biore",
    category: "household",
    store: "Drugstore",
    priceJpy: 1078,
    volumeMl: 150,
    weightG: null,
    servings: null,
    nutrition: null,
    skincare: {
      spf: 50,
      fragranceFree: false,
      alcoholFree: false,
      irritationRisk: "medium",
      keyIngredients: ["methoxycinnamate"],
    },
    allergens: [],
    additives: ["alcohol", "fragrance"],
    tags: ["body spray", "sunscreen", "convenient", "outdoor"],
  },
  {
    id: "house-005",
    name: "Lion White Quick Toilet Brush",
    nameJa: "ライオン ルックプラス お掃除シート for TOILET",
    brand: "Lion",
    category: "household",
    store: "Supermarket",
    priceJpy: 328,
    volumeMl: null,
    weightG: null,
    servings: null,
    nutrition: null,
    skincare: null,
    allergens: [],
    additives: [],
    tags: ["cleaning", "toilet", "sheets", "disposable"],
  },
  {
    id: "house-006",
    name: "Pantene Pro-V Moisture Boost Shampoo",
    nameJa: "パンテーン プロブイ モイスチャースムース ケア シャンプー",
    brand: "P&G",
    category: "household",
    store: "Supermarket",
    priceJpy: 748,
    volumeMl: 400,
    weightG: null,
    servings: null,
    nutrition: null,
    skincare: null,
    allergens: [],
    additives: ["fragrance", "preservative"],
    tags: ["shampoo", "hair care", "moisturizing", "popular"],
  },
  {
    id: "house-007",
    name: "Mandom Gatsby Face Wash Icy Type",
    nameJa: "マンダム ギャツビー 洗顔フォーム アイスタイプ",
    brand: "Mandom",
    category: "household",
    store: "Drugstore",
    priceJpy: 548,
    volumeMl: 130,
    weightG: null,
    servings: null,
    nutrition: null,
    skincare: {
      spf: null,
      fragranceFree: false,
      alcoholFree: false,
      irritationRisk: "medium",
      keyIngredients: ["menthol", "charcoal"],
    },
    allergens: [],
    additives: ["menthol", "fragrance"],
    tags: ["face wash", "men", "cooling", "pore cleansing"],
  },
];

export function getProductById(id: string): Product | undefined {
  return DEMO_PRODUCTS.find((p) => p.id === id);
}

export function getProductsByCategory(category: string): Product[] {
  return DEMO_PRODUCTS.filter((p) => p.category === category);
}
